// Question Bank for FAST University Entry Test
// Structure: Each section contains arrays of questions with id, q (question), o (options), a (correct answer index)

const QUESTION_BANK = {
    "Advanced Mathematics": [
        {"id":1,"q":"What is the derivative of sin(x)?","o":["cos(x)","-cos(x)","sin(x)","-sin(x)"],"a":0},
        {"id":2,"q":"What is the integral of e^x dx?","o":["e^x + C","xe^x + C","e^(x+1) + C","ln|x| + C"],"a":0},
        {"id":3,"q":"If the roots of x² + 5x + 6 = 0 are α and β, find α + β.","o":["-5","6","5","-6"],"a":0},
        {"id":4,"q":"The value of lim x→0 (sin x)/x is:","o":["0","1","Infinity","Does not exist"],"a":1},
        {"id":5,"q":"Find ∫x² e^x dx:","o":["e^x(x² - 2x + 2) + C","e^x(2x² - 1) + C","e^x(2x + 1) + C","2x e^x x² + C"],"a":0},
        {"id":6,"q":"If the focus of the parabola is (0, -3), then it is a:","o":["Cup up parabola","Cup down parabola","Left open parabola","Right open parabola"],"a":1},
        {"id":7,"q":"Evaluate: 1/(1 - sin²θ) + 1/(1 + sin²θ) = ?","o":["1/(1 + sin²θ)","2/(1 - sin²θ)","2/(1 - sin⁴θ)","1/(1 + tan²θ)"],"a":2},
        {"id":8,"q":"Find d/dx (tan²x):","o":["2 tan x sec² x","2 tan x sec² x","tan x sec² x","2 tan² x sec² x"],"a":0},
        {"id":9,"q":"Evaluate ∫ from 0 to ln e² of x² e^(3x³) dx:","o":["1/9 (e²⁴ - 1)","9 e^(3x²)","1/9 (e⁴¹ - 2)","e^(3x²)"],"a":0},
        {"id":10,"q":"Find the distance between points (2, -6) and (6, -3):","o":["25","5","4","16"],"a":1},
        {"id":11,"q":"Slope of the line given by 5x/2 + 7y/2 = 49/10 is:","o":["-5/7","6","7/5","11"],"a":0},
        {"id":12,"q":"Standard equation of hyperbola with center at (0,0):","o":["x²/a² + y²/b² = 1","x²/a² - y²/b² = 1","x²/a² + y² = 1","x²/a² - y² = 1"],"a":1},
        {"id":13,"q":"Find the equation of the tangent to the curve 3x² - 4y² = 12 at (4, -3):","o":["x + y = 1","x - y = -1","x + y = -1","x - y = 1"],"a":2},
        {"id":14,"q":"Find d/dx [f(x) · g(x)]²:","o":["[f(x) · g(x)]²","2 [f(x) · g(x)] [f(x) d/dx g(x) + g(x) d/dx f(x)]","[f(x) · g(x)]⁻¹","[f(x) d/dx g(x) + g(x) d/dx f(x)]"],"a":1},
        {"id":15,"q":"If z = -7 + √3 i, find (z - conjugate(z))³:","o":["343","-343","-12√3 i","-24√3 i"],"a":1},
        {"id":16,"q":"If f(x) = x³ + cos x then f(x) is:","o":["An odd function","Neither odd nor even","An even function","A constant function"],"a":1},
        {"id":17,"q":"Evaluate lim x→3 of (3x²)/2:","o":["0","27/2","∞","-11/2"],"a":1},
        {"id":18,"q":"Find f'(x), if f(x) = sin³ x:","o":["3 sin² x cos x","3 sin² x cos x","3 sin x cos x","½ sin² x cos² x"],"a":0},
        {"id":19,"q":"If dy = ln x dx and the slope at (x, y) is same as when it is parallel to x-axis, find x:","o":["1","0","e","1/e"],"a":0},
        {"id":20,"q":"The derivative of cos² 3x is:","o":["-6 cos 3x sin 3x","6 cos 3x sin x","-2 cos 3x sin x","None"],"a":0},
        {"id":21,"q":"Curve y = x² - 8 has:","o":["Minimum value only","Maximum value only","Both maximum and minimum","No extreme value"],"a":0},
        {"id":22,"q":"The equation of the line which is parallel to x-axis and 5 units above it is:","o":["y = 5","y = -5","x = -5","x = 5"],"a":0},
        {"id":23,"q":"The derivative of y = cos x is equal to:","o":["-sin x","sin x","-tan x","cos x"],"a":0},
        {"id":24,"q":"If α, β are roots of x² - 2x + 1 = 0, then (α + β)² equals:","o":["4","-2","1","2"],"a":0},
        {"id":25,"q":"The possible number of root(s) of equation x^(2/3) = 9 is/are:","o":["one","two","no roots","infinite roots"],"a":1},
        {"id":26,"q":"The real quadratic equation whose coefficients are rational and one root is √2 + √9, is:","o":["x² - 7x - 11 = 0","x² - 10x + 7 = 0","-x² + 2x - 1 = 0","x² - 13x - 15 = 0"],"a":1},
        {"id":27,"q":"ω being the complex cube roots of unity, which statements are true?","o":["I only","II only","I and II","I and III"],"a":2},
        {"id":28,"q":"If one root of 5x² + 7x - t² + 196 = 0 is zero, then t is equal to:","o":["-14","±14","0","14"],"a":1},
        {"id":29,"q":"Express (x+1) / (x(x+2)²) as partial fractions:","o":["A/x + B/(x+2) + C/(x+2)²","A/x + B/(x+2)","A/x + B/(x+2) + Cx + D/(x+2)²","A/x + Bx + C/(x+2)²"],"a":0},
        {"id":30,"q":"√(x + 2) = -1, then real root(s) of the equation is/are:","o":["one","two","three","no roots"],"a":3},
        {"id":31,"q":"If α, β are roots of 3x² + 2x + 5 = 0, then sum of α + 1/α and β + 1/β is:","o":["-8/15","8/5","-2/3","5/3"],"a":0},
        {"id":32,"q":"If the equation 7x² + 15x + k = 0 has roots √α and 1/√α, then k is:","o":["-11","2","7","15"],"a":2},
        {"id":33,"q":"If the sum of a number and its reciprocal is 41/20, then the number is:","o":["5/4","-5/4","-4/5","4/5"],"a":0},
        {"id":34,"q":"If f(x) = x^4 - 4x^3 + 6x^2 - 4x + 1, then f'(1) = ?","o":["0","4","1","-1"],"a":0},
        {"id":35,"q":"Find the value of sin 2θ if cos θ = 3/5 and θ is in the first quadrant:","o":["24/25","24/25","24/13","24/15"],"a":0},
        {"id":36,"q":"If f(x) = ln(x^2 + 1), find f'(1):","o":["1","2","1/2","3/2"],"a":0},
        {"id":37,"q":"Evaluate ∫ x e^x dx:","o":["(x-1)e^x + C","e^x + C","x e^x + C","x² e^x + C"],"a":0},
        {"id":38,"q":"If tan θ = 1, find sin 2θ:","o":["1","0","-1","2"],"a":0},
        {"id":39,"q":"For what values of k will the equation kx² + 2kx + 4 = 0 have equal roots?","o":["k = 0","k = 1","k = 2","k = 4"],"a":3},
        {"id":40,"q":"If the vertex of parabola y = x² + bx + c lies on the x-axis, then:","o":["b² = 4c","b² = -4c","b = 0","c = 0"],"a":0},
        {"id":41,"q":"If the distance between (1,2) and (x,6) is 5, find x:","o":["3","4","5","-2 or 4"],"a":3},
        {"id":42,"q":"If sin θ = 3/5, find cos θ:","o":["4/5","3/5","1/5","2/5"],"a":0},
        {"id":43,"q":"The sum of the first n natural numbers is given by:","o":["n(n+1)/2","n²/2","n(n-1)/2","n²"],"a":0},
        {"id":44,"q":"If the roots of x² + px + q = 0 are equal, then:","o":["p² = 4q","p² = q","p = q","p²=-4q"],"a":0},
        {"id":45,"q":"Find d/dx of ln(x):","o":["1/x","ln x","x","-1/x"],"a":0},
        {"id":46,"q":"The value of cos 60° is:","o":["1/2","√3/2","1","0"],"a":0},
        {"id":47,"q":"The equation of the circle with center (3,-2) and radius 5 is:","o":["(x-3)² + (y+2)² = 25","(x+3)² + (y-2)² = 25","(x-3)² + (y-2)² = 25","(x+3)² + (y+2)² = 25"],"a":0},
        {"id":48,"q":"If A = {1,2,3} and B = {3,4,5}, then A ∩ B = ?","o":["{1,2,3,4,5}","{3}","{1,2,3}","{4,5}"],"a":1},
        {"id":49,"q":"The sum of the angles of a triangle is:","o":["180°","90°","360°","270°"],"a":0},
        {"id":50,"q":"The solution to x² = 16 is:","o":["x = ±4","x = 4","x = 0","x = -4"],"a":0}
    ],
    
    "Basic Mathematics": [
        {"id":1,"q":"6.09 – 4.693 = ?","o":["1.397","1.403","1.407","1.413"],"a":0},
        {"id":2,"q":"If p = 0.2 and n = 100, what is (1/p) – n?","o":["0","3","5","0.4"],"a":0},
        {"id":3,"q":"Each of 4 subsidiaries has credit of $700,000 and each of 3 others has $112,000. What is average credit?","o":["$448,000","$406,000","$313,600","$406,500"],"a":0},
        {"id":4,"q":"If x satisfies both x² – 3x + 2 = 0 and x² – x – 2 = 0, what is x?","o":["1","2","-1","-2"],"a":1},
        {"id":5,"q":"A student traveled 1/5 by foot, 2/3 by bus, and remaining 8 km by car. Total distance?","o":["30 km","45 km","60 km","90 km"],"a":2},
        {"id":6,"q":"Elevator limit is 2000 lbs. Half riders average 180 lbs, others 215 lbs. Max number of riders?","o":["8","9","10","11"],"a":2},
        {"id":7,"q":"After 10% tax on income above $3000, net income is $12,000. Original income?","o":["$13,000","$13,300","$12,900","$10,000"],"a":0},
        {"id":8,"q":"Calculate: [7 – (6 – (5 + 4 – 3) + 2)] – 1 = ?","o":["0","1","2","-2"],"a":1},
        {"id":9,"q":"Camera costs $209, lens $69, together $239. What percent saved?","o":["14%","16%","29%","33%"],"a":0},
        {"id":10,"q":"0.497 marks = $1. Value of 350 marks?","o":["$174","$176","$704","$524"],"a":2},
        {"id":11,"q":"Cylinder radius 2m, height 1m filled with oil. Cans radius 0.5m, height 4m. How many cans filled?","o":["1","2","4","8"],"a":0},
        {"id":12,"q":"8 consecutive odd integers, 7th term is 9. Sum of all terms?","o":["36","40","44","48"],"a":1},
        {"id":13,"q":"Floor m by n covered by rug except strip p wide on edges. Area of rug?","o":["mn – 2p(m+n)","(m–2p)(n–2p)","mn – p(m+n)","(m–p)(n–p)"],"a":1},
        {"id":14,"q":"R can do job in 9 hrs; R and S together in 6 hrs. How long for S alone?","o":["18 hrs","12 hrs","9 hrs","6 hrs"],"a":0},
        {"id":15,"q":"Family borrowed $325 after $75 down payment. Paid 23 months $16 + final $9. Interest percent?","o":["6%","12%","14%","16%"],"a":1},
        {"id":16,"q":"If y = (2x² – 4x) / x, express x in terms of y (x ≠ 0).","o":["2y","y","(y + 2)/2","(y – 2)/2"],"a":2},
        {"id":17,"q":"Solution Y is 30% liquid X, 70% water. After evaporating 2 kg water from 8 kg solution, then adding 2 kg solution, new % liquid X?","o":["30%","33%","37%","40%"],"a":2},
        {"id":18,"q":"Calculate 0.37 + 0.103 + 0.01 = ?","o":["0.004","0.02775","0.483","0.6036"],"a":2},
        {"id":19,"q":"Triangle ACD has sides 3; AB =1. Find area of region BCDE.","o":["3.4","4.9","7.2","9.3"],"a":1},
        {"id":20,"q":"If 5 apples cost 20 rupees, how much do 8 apples cost?","o":["28","30","32","35"],"a":2}
    ],
    
    "IQ & Analytical Skills": [
        {"id":1,"q":"What is the next number in the sequence? 2, 6, 12, 20, 30, ?","o":["36","40","42","48"],"a":2},
        {"id":2,"q":"Which shape does not belong? A) Square B) Rectangle C) Rhombus D) Trapezium","o":["Square","Rectangle","Rhombus","Trapezium"],"a":3},
        {"id":3,"q":"Find the next letter: D, G, J, M, ?","o":["O","P","Q","R"],"a":2},
        {"id":4,"q":"If 3^x = 81, then x = ?","o":["2","3","4","5"],"a":2},
        {"id":5,"q":"A cube has numbers 1 to 6 on each face. If 1 is opposite 6, 2 opposite 5, and 3 opposite 4, what number is adjacent to face 1 and 3?","o":["2","4","5","6"],"a":0},
        {"id":6,"q":"Find the missing number: 1, 4, 9, 16, 25, ?","o":["30","35","36","49"],"a":2},
        {"id":7,"q":"Which letter comes next? Z, X, U, Q, L, ?","o":["F","G","H","I"],"a":0},
        {"id":8,"q":"Find the missing number in the matrix:\n| 2 | 3 | 5 |\n| 4 | 6 | ? |\n| 6 | 9 | 15 |","o":["8","9","10","12"],"a":3},
        {"id":9,"q":"If the word \"FALL\" is reflected in a mirror held vertically, what will it look like?","o":["LLAf","LLAF","LLAF","LLAF"],"a":1},
        {"id":10,"q":"Which number does not belong? 11, 13, 17, 19, 21, 23","o":["11","17","19","21"],"a":3},
        {"id":11,"q":"A sequence of shapes shows: Triangle, Square, Pentagon, Hexagon, ? What comes next?","o":["Heptagon","Octagon","Nonagon","Decagon"],"a":0},
        {"id":12,"q":"What comes next? 7, 14, 28, 56, ?","o":["70","84","112","120"],"a":2},
        {"id":13,"q":"Find the odd one out: 2, 3, 5, 7, 11, 15, 17","o":["11","15","3","7"],"a":1},
        {"id":14,"q":"If 5 apples cost 20 rupees, how much do 8 apples cost?","o":["28","30","32","35"],"a":2},
        {"id":15,"q":"In a code language, 'CAT' is written as '3120', how is 'DOG' written?","o":["4157","4158","4167","4168"],"a":2},
        {"id":16,"q":"What is the next figure in this sequence: Circle, Triangle, Square, Pentagon, ?","o":["Hexagon","Heptagon","Octagon","Nonagon"],"a":0},
        {"id":17,"q":"How many triangles are there in a figure made of 4 small triangles inside a larger triangle?","o":["4","5","6","7"],"a":3},
        {"id":18,"q":"What number completes the series? 1, 4, 9, 16, 25, 36, ?","o":["42","48","49","64"],"a":2},
        {"id":19,"q":"If in a certain language, 'MANGO' is coded as 'NBOHP', how is 'APPLE' coded?","o":["BQQMF","AQPMF","BQQLE","BQQLE"],"a":0},
        {"id":20,"q":"Complete the analogy: Finger is to Hand as Leaf is to ?","o":["Tree","Branch","Root","Flower"],"a":0}
    ],
    
    "English": [
        {"id":1,"q":"DOOR : WALL","o":["toll : road","guard : border","gate : fence","bridge : river","key : lock"],"a":2},
        {"id":2,"q":"CARNIVORE : MEAT","o":["carnivore : vegetables","herbivore : plants","vegetarian : vitamins","botanist : herbs","pollinator : plants"],"a":1},
        {"id":3,"q":"Synonym of ACCESS","o":["agreement","rapidity","welcome","approach","incompetence"],"a":3},
        {"id":4,"q":"Synonym of PRUDENT","o":["generous","overcritical","famous","dull","cautious"],"a":4},
        {"id":5,"q":"Antonym of ANIMATED","o":["worthy","humorous","dull","lengthy","realistic"],"a":2},
        {"id":6,"q":"Antonym of EXTROVERT","o":["clown","hero","ectomorph","neurotic","introvert"],"a":4},
        {"id":7,"q":"The four close friends decided to attend different colleges. At first, they were ______ to leave each other, but eventually they were glad they each made their own ______.","o":["excited...decision","reluctant...choice","frustrated...plan","happy...friendship","depressed...bond"],"a":1},
        {"id":8,"q":"Samuel is loyal to his roots (he always has been), and is resistant to change. Raphael, however, favors a less traditional, more ______ approach.","o":["patient","contemporary","diverse","liberal","forgiving"],"a":1},
        {"id":9,"q":"The play was made __________ a movie.","o":["by","into","with","for","across"],"a":1},
        {"id":10,"q":"The whole nation was _________ the president.","o":["behind","after","before","for","in front of"],"a":0},
        {"id":11,"q":"Choose the correct sentence:","o":["He don't like to play football.","He doesn't likes to play football.","He doesn't like to play football.","He don't likes to play football.","He isn't like to play football."],"a":2},
        {"id":12,"q":"Choose the word that best fits the sentence:\n\"Despite his ________ efforts, the project failed.\"","o":["laziness","diligent","diligence","lazy","diligently"],"a":2},
        {"id":13,"q":"Fill in the blank with the correct preposition:\n\"She is afraid _____ spiders.\"","o":["for","of","from","with","about"],"a":1},
        {"id":14,"q":"Identify the figure of speech:\n\"The wind whispered through the trees.\"","o":["Simile","Metaphor","Personification","Alliteration","Onomatopoeia"],"a":2},
        {"id":15,"q":"Comprehension:\n\"Mira always loved helping others. She spent most of her weekends volunteering at the animal shelter. Her dedication inspired many people around her.\"\n\nWhat quality of Mira is highlighted in the passage?","o":["Selfishness","Laziness","Kindness","Anger","Greed"],"a":2},
        {"id":16,"q":"Choose the correct passive form of the sentence:\n\"They will finish the work tomorrow.\"","o":["The work is finished by them tomorrow.","The work will be finished by them tomorrow.","The work was finished by them tomorrow.","The work has been finished by them tomorrow.","The work will be finishing by them tomorrow."],"a":1},
        {"id":17,"q":"Choose the correct synonym of 'OBSTACLE':","o":["advantage","hurdle","benefit","gift","help"],"a":1},
        {"id":18,"q":"Choose the correctly punctuated sentence:","o":["Lets eat grandma.","Let's eat grandma.","Let's eat, grandma.","Lets eat, grandma.","Let's eat grandma!"],"a":2},
        {"id":19,"q":"Fill in the blank:\n\"He has been working here ______ 2015.\"","o":["for","since","from","by","after"],"a":1},
        {"id":20,"q":"Choose the correct word:\n\"She was ______ by the news.\"","o":["surprise","surprised","surprising","surprisingly","surpriser"],"a":1},
        {"id":21,"q":"Critical Thinking:\n\"If all mammals are warm-blooded, and dolphins are mammals, which of the following is true?\"","o":["Dolphins are cold-blooded.","All dolphins are fish.","Dolphins are warm-blooded.","Mammals are cold-blooded.","Dolphins lay eggs."],"a":2},
        {"id":22,"q":"Comprehension:\n\"Ali had to choose between going to the party and studying for his exam. He chose to study.\"\n\nWhat does Ali's choice show about his personality?","o":["He is irresponsible.","He is lazy.","He is disciplined.","He is careless.","He is dishonest."],"a":2},
        {"id":23,"q":"Identify the error:\n\"She don't want to go to the market.\"","o":["She","don't","want","to","market"],"a":1},
        {"id":24,"q":"Choose the correct form:\n\"Neither of the boys ______ ready.\"","o":["are","is","were","be","am"],"a":1},
        {"id":25,"q":"Choose the correct antonym of 'VIGOROUS':","o":["weak","strong","active","energetic","powerful"],"a":0},
        {"id":26,"q":"Choose the correct word to fill in:\n\"He _______ his keys yesterday.\"","o":["lose","lost","loses","losing","loss"],"a":1},
        {"id":27,"q":"Comprehension:\n\"Sara enjoys painting and often spends hours in her studio. It helps her relax and express her feelings.\"\n\nWhy does Sara paint?","o":["To earn money","To relax and express feelings","To compete in contests","To spend time with friends","Because she is forced"],"a":1},
        {"id":28,"q":"Choose the correct conjunction:\n\"I wanted to go to the park, ______ it started to rain.\"","o":["but","and","or","so","because"],"a":0},
        {"id":29,"q":"Identify the adjective in the sentence:\n\"The quick brown fox jumps over the lazy dog.\"","o":["jumps","fox","quick","over","dog"],"a":2},
        {"id":30,"q":"Fill in the blank with the correct form:\n\"If I ______ rich, I would travel the world.\"","o":["am","were","was","be","being"],"a":1}
    ]
};

// Export for use in main script
if (typeof module !== 'undefined' && module.exports) {
    module.exports = QUESTION_BANK;
} 