// Question Bank for FAST University Entry Test
// Structure: Each section contains arrays of questions with id, q (question), o (options), a (correct answer index)

const QUESTION_BANK = {
    "Advanced Mathematics": [
        {"id":1,"q":"What is the derivative of sin(x)?","o":["cos(x)","-cos(x)","sin(x)","-sin(x)"],"a":0},
        {"id":2,"q":"What is the integral of e^x dx?","o":["e^x + C","xe^x + C","e^(x+1) + C","ln|x| + C"],"a":0},
        {"id":3,"q":"If the roots of x² + 5x + 6 = 0 are α and β, find α + β.","o":["-5","6","5","-6"],"a":0},
        {"id":4,"q":"The value of lim x→0 (sin x)/x is:","o":["0","1","∞","Does not exist"],"a":1},
        {"id":5,"q":"Find ∫x² e^x dx:","o":["e^x(x² - 2x + 2) + C","e^x(x² + 2x + 2) + C","x²e^x + C","(x² - 1)e^x + C"],"a":0},
        {"id":6,"q":"If the focus of the parabola is (0, -3), then it is a:","o":["Upward opening parabola","Downward opening parabola","Left opening parabola","Right opening parabola"],"a":1},
        {"id":7,"q":"Evaluate: 1/(1 - sin²θ) + 1/(1 + sin²θ) = ?","o":["2/(1 + sin²θ)","2/(1 - sin²θ)","2/(1 - sin⁴θ)","2 sec²θ"],"a":2},
        {"id":8,"q":"Find d/dx (tan²x):","o":["2 tan x sec² x","tan x sec² x","2 tan² x sec² x","2 tan x sec x"],"a":0},
        {"id":9,"q":"If f(x) = x³ + 2x² - 5x + 1, find f'(2):","o":["19","15","23","11"],"a":0},
        {"id":10,"q":"Find the distance between points (2, -6) and (6, -3):","o":["25","5","7","16"],"a":1},
        {"id":11,"q":"Slope of the line given by 5x + 7y = 49 is:","o":["-5/7","5/7","7/5","-7/5"],"a":0},
        {"id":12,"q":"Standard equation of hyperbola with center at (0,0):","o":["x²/a² + y²/b² = 1","x²/a² - y²/b² = 1","(x-h)²/a² - (y-k)²/b² = 1","x² - y² = 1"],"a":1},
        {"id":13,"q":"Find the equation of the tangent to the curve y = x² at point (2, 4):","o":["y = 4x - 4","y = 2x + 4","y = 4x + 4","y = x + 2"],"a":0},
        {"id":14,"q":"Find d/dx [f(x) · g(x)]²:","o":["2[f(x)g(x)][f'(x)g(x) + f(x)g'(x)]","[f(x) · g(x)]²","2[f(x) · g(x)]","[f'(x) · g'(x)]²"],"a":0},
        {"id":15,"q":"If z = -7 + √3 i, find |z|:","o":["√52","7","√3","√46"],"a":0},
        {"id":16,"q":"If f(x) = x³ + cos x then f(x) is:","o":["An odd function","Neither odd nor even","An even function","A periodic function"],"a":1},
        {"id":17,"q":"Evaluate lim x→3 of (x² + 2x - 15)/(x - 3):","o":["0","8","∞","Does not exist"],"a":1},
        {"id":18,"q":"Find f'(x), if f(x) = sin³ x:","o":["3 sin² x cos x","cos³ x","3 sin x cos² x","sin² x cos x"],"a":0},
        {"id":19,"q":"If y = ln(x²), find dy/dx:","o":["2/x","1/x²","2x","ln(2x)"],"a":0},
        {"id":20,"q":"The derivative of cos² 3x is:","o":["-6 cos 3x sin 3x","-3 sin 6x","6 cos 3x sin 3x","-6 sin 3x cos 3x"],"a":0},
        {"id":21,"q":"Function y = x² - 8 has:","o":["Minimum value at x = 0","Maximum value at x = 0","No extreme values","Minimum at x = 2"],"a":0},
        {"id":22,"q":"The equation of the line which is parallel to x-axis and 5 units above it is:","o":["y = 5","y = -5","x = 5","x = -5"],"a":0},
        {"id":23,"q":"The derivative of y = cos x is equal to:","o":["-sin x","sin x","cos x","-cos x"],"a":0},
        {"id":24,"q":"If α, β are roots of x² - 2x + 1 = 0, then α + β equals:","o":["2","1","4","0"],"a":0},
        {"id":25,"q":"The number of real solution(s) of equation x^(2/3) = 9 is/are:","o":["one","two","three","none"],"a":1},
        {"id":26,"q":"Find ∫(2x + 3)dx:","o":["x² + 3x + C","2x² + 3x + C","x² + 6x + C","2x + 3x² + C"],"a":0},
        {"id":27,"q":"If sin θ = 3/5 and θ is in first quadrant, find cos θ:","o":["4/5","3/5","5/4","5/3"],"a":0},
        {"id":28,"q":"The value of ∫₀¹ x² dx is:","o":["1/3","1","1/2","2/3"],"a":0},
        {"id":29,"q":"Express (x+1) / (x(x+2)²) as partial fractions. The form is:","o":["A/x + B/(x+2) + C/(x+2)²","A/x + B/(x+2)","A/x + (Bx+C)/(x+2)²","A/x + B(x+2)²"],"a":0},
        {"id":30,"q":"√(x + 2) = -1, the number of real solution(s) is:","o":["none","one","two","three"],"a":0},
        {"id":31,"q":"If α, β are roots of 3x² + 2x + 5 = 0, find α + β:","o":["-2/3","2/3","5/3","-5/3"],"a":0},
        {"id":32,"q":"Find the area under curve y = x² from x = 0 to x = 2:","o":["8/3","4","8","16/3"],"a":0},
        {"id":33,"q":"If the sum of a number and its reciprocal is 41/20, find the number:","o":["5/4","4/5","20/41","41/20"],"a":0},
        {"id":34,"q":"If f(x) = x⁴ - 4x³ + 6x² - 4x + 1, then f'(1) = ?","o":["0","1","2","-2"],"a":0},
        {"id":35,"q":"Find the value of sin 2θ if cos θ = 3/5 and θ is in the first quadrant:","o":["24/25","7/25","24/13","12/13"],"a":0},
        {"id":36,"q":"If f(x) = ln(x² + 1), find f'(1):","o":["1","2","1/2","3/2"],"a":0},
        {"id":37,"q":"Evaluate ∫ x e^x dx using integration by parts:","o":["(x-1)e^x + C","xe^x + C","(x+1)e^x + C","x²e^x + C"],"a":0},
        {"id":38,"q":"If tan θ = 1, find the value of sin 2θ:","o":["1","√2/2","0","1/2"],"a":0},
        {"id":39,"q":"For what value of k will kx² + 2kx + 4 = 0 have equal roots?","o":["k = 0","k = 1","k = 2","k = 4"],"a":3},
        {"id":40,"q":"If the vertex of parabola y = x² + bx + c lies on the x-axis, then:","o":["b² = 4c","b² = -4c","b = c","c = 0"],"a":0},
        {"id":41,"q":"If the distance between (1,2) and (x,6) is 5, find possible values of x:","o":["4 only","-2 only","4 or -2","3 or 5"],"a":2},
        {"id":42,"q":"If sin θ = 3/5, find cos θ (θ in first quadrant):","o":["4/5","±4/5","3/4","5/3"],"a":0},
        {"id":43,"q":"The sum of the first n natural numbers is:","o":["n(n+1)/2","n²","n(n-1)/2","(n+1)²/2"],"a":0},
        {"id":44,"q":"If the roots of x² + px + q = 0 are equal, then the discriminant is:","o":["p² - 4q = 0","p² + 4q = 0","p² = q","p = q"],"a":0},
        {"id":45,"q":"Find d/dx of ln(x):","o":["1/x","ln x","x","1/x²"],"a":0},
        {"id":46,"q":"The value of cos 60° is:","o":["1/2","√3/2","√2/2","1"],"a":0},
        {"id":47,"q":"The equation of the circle with center (3,-2) and radius 5 is:","o":["(x-3)² + (y+2)² = 25","(x+3)² + (y-2)² = 25","x² + y² = 25","(x-3)² + (y-2)² = 5"],"a":0},
        {"id":48,"q":"If A = {1,2,3} and B = {3,4,5}, then A ∩ B = ?","o":["{3}","{1,2,3,4,5}","{1,2}","{4,5}"],"a":0},
        {"id":49,"q":"The sum of interior angles of a triangle is:","o":["180°","90°","360°","120°"],"a":0},
        {"id":50,"q":"The solutions to x² = 16 are:","o":["x = ±4","x = 4 only","x = -4 only","x = 8"],"a":0}
    ],
    
    "Basic Mathematics": [
        {"id":1,"q":"Calculate: 6.09 - 4.693 = ?","o":["1.397","1.403","1.407","1.413"],"a":0},
        {"id":2,"q":"If p = 0.2 and n = 100, what is (1/p) - n?","o":["-95","3","5","0.4"],"a":0},
        {"id":3,"q":"Four subsidiaries have credit of $700,000 each and three others have $112,000 each. What is average credit?","o":["$448,000","$406,000","$313,600","$500,000"],"a":0},
        {"id":4,"q":"Find x if x satisfies both x² - 3x + 2 = 0 and x² - x - 2 = 0:","o":["1","2","-1","no solution"],"a":1},
        {"id":5,"q":"A student traveled 1/5 by foot, 2/3 by bus, and remaining 8 km by car. Find total distance:","o":["30 km","45 km","60 km","40 km"],"a":2},
        {"id":6,"q":"Elevator limit is 2000 lbs. Half riders average 180 lbs, others 215 lbs. Maximum number of riders?","o":["8","9","10","11"],"a":2},
        {"id":7,"q":"After 10% tax on income above $3000, net income is $12,000. Find original income:","o":["$13,000","$13,300","$12,900","$15,000"],"a":0},
        {"id":8,"q":"Calculate: [7 - (6 - (5 + 4 - 3) + 2)] - 1 = ?","o":["0","1","2","-1"],"a":1},
        {"id":9,"q":"Camera costs $209, lens $69, together $239. What percent is saved?","o":["14%","16%","10%","20%"],"a":0},
        {"id":10,"q":"0.497 marks = $1. What is the value of 350 marks?","o":["$174","$176","$704","$350"],"a":2},
        {"id":11,"q":"Cylinder radius 2m, height 1m filled with oil. How many cans (radius 0.5m, height 4m) can be filled?","o":["1","2","4","3"],"a":0},
        {"id":12,"q":"8 consecutive odd integers where 7th term is 9. Find sum of all terms:","o":["8","40","32","16"],"a":1},
        {"id":13,"q":"Floor m×n covered by rug except strip p wide around edges. Area of rug?","o":["mn - 2p(m+n)","(m-2p)(n-2p)","mn - p(m+n)","mn - 4p²"],"a":1},
        {"id":14,"q":"R can do job in 9 hrs; R and S together in 6 hrs. How long for S alone?","o":["18 hrs","15 hrs","12 hrs","21 hrs"],"a":0},
        {"id":15,"q":"Family borrowed $325 after $75 down payment. Paid 23 months at $16 + final $9. Find interest percent:","o":["6%","12%","14%","8%"],"a":1},
        {"id":16,"q":"If y = (2x² - 4x) / x, express x in terms of y (x ≠ 0):","o":["(y + 4)/2","y/2","(y + 2)/2","2y"],"a":2},
        {"id":17,"q":"Solution Y is 30% liquid X, 70% water. After evaporating 2 kg water from 8 kg solution Y, then adding 2 kg solution Y, find new % of liquid X:","o":["30%","33%","37%","35%"],"a":2},
        {"id":18,"q":"Calculate: 0.37 + 0.103 + 0.01 = ?","o":["0.473","0.483","0.493","0.503"],"a":1},
        {"id":19,"q":"A rectangle has length 12 cm and width 8 cm. Find its area:","o":["96 cm²","20 cm²","40 cm²","80 cm²"],"a":0},
        {"id":20,"q":"If 5 apples cost 20 rupees, how much do 8 apples cost?","o":["28","30","32","25"],"a":2}
    ],
    
    "IQ & Analytical Skills": [
        {"id":1,"q":"What is the next number in the sequence? 2, 6, 12, 20, 30, ?","o":["36","40","42","48"],"a":2},
        {"id":2,"q":"Which shape does not belong? A) Square B) Rectangle C) Rhombus D) Trapezium","o":["Square","Rectangle","Rhombus","Trapezium"],"a":3},
        {"id":3,"q":"Find the next letter: D, G, J, M, ?","o":["N","O","P","Q"],"a":2},
        {"id":4,"q":"If 3^x = 81, then x = ?","o":["2","3","4","5"],"a":2},
        {"id":5,"q":"A cube has numbers 1 to 6. If 1 is opposite 6, 2 opposite 5, and 3 opposite 4, which number is adjacent to both 1 and 3?","o":["2","4","5","6"],"a":0},
        {"id":6,"q":"Find the missing number: 1, 4, 9, 16, 25, ?","o":["30","35","36","49"],"a":2},
        {"id":7,"q":"Which letter comes next? Z, X, U, Q, L, ?","o":["F","G","H","I"],"a":0},
        {"id":8,"q":"Complete the pattern: 2, 4, 8, 16, ?","o":["24","30","32","64"],"a":2},
        {"id":9,"q":"If BOOK is coded as 2551511, how is PEN coded?","o":["16514","165114","1651411","16514"],"a":0},
        {"id":10,"q":"Which number does not belong? 11, 13, 17, 19, 21, 23","o":["11","17","19","21"],"a":3},
        {"id":11,"q":"A shape sequence shows: Triangle, Square, Pentagon, Hexagon. What comes next?","o":["Heptagon","Octagon","Circle","Diamond"],"a":0},
        {"id":12,"q":"What comes next? 7, 14, 28, 56, ?","o":["70","84","112","128"],"a":2},
        {"id":13,"q":"Find the odd one out: 2, 3, 5, 7, 11, 15, 17","o":["11","15","3","7"],"a":1},
        {"id":14,"q":"Complete the series: 100, 81, 64, 49, ?","o":["36","25","16","9"],"a":0},
        {"id":15,"q":"In a code, CAT = 3120. How is DOG written?","o":["4157","4158","4167","4175"],"a":2},
        {"id":16,"q":"If Monday is coded as 123456, how is FRIDAY coded?","o":["895456","785456","695456","595456"],"a":0},
        {"id":17,"q":"How many squares are in a 3×3 grid?","o":["9","12","14","16"],"a":2},
        {"id":18,"q":"Complete the sequence: 1, 1, 2, 3, 5, 8, ?","o":["11","12","13","15"],"a":2},
        {"id":19,"q":"If MANGO is coded as NBOHP, how is APPLE coded?","o":["BQQMF","BQQLE","CQQMF","BPPMF"],"a":0},
        {"id":20,"q":"Complete the analogy: Finger is to Hand as Leaf is to ?","o":["Tree","Branch","Stem","Root"],"a":0}
    ],
    
    "English": [
        {"id":1,"q":"DOOR : WALL :: ? : ?","o":["window : building","gate : fence","key : lock","handle : knob"],"a":1},
        {"id":2,"q":"CARNIVORE : MEAT :: ? : ?","o":["herbivore : plants","vegetarian : vitamins","omnivore : everything","predator : prey"],"a":0},
        {"id":3,"q":"Choose the synonym of ACCESS:","o":["agreement","entry","welcome","approach"],"a":3},
        {"id":4,"q":"Choose the synonym of PRUDENT:","o":["generous","careless","famous","cautious"],"a":3},
        {"id":5,"q":"Choose the antonym of ANIMATED:","o":["lively","humorous","dull","lengthy"],"a":2},
        {"id":6,"q":"Choose the antonym of EXTROVERT:","o":["social","hero","outgoing","introvert"],"a":3},
        {"id":7,"q":"Fill in the blanks: The friends decided to attend different colleges. At first, they were ______ to leave each other, but eventually they were glad they each made their own ______.","o":["excited...decision","reluctant...choice","frustrated...plan","happy...friendship"],"a":1},
        {"id":8,"q":"Samuel is traditional and resistant to change. Raphael, however, favors a less traditional, more ______ approach.","o":["patient","contemporary","diverse","conservative"],"a":1},
        {"id":9,"q":"The play was made __________ a movie.","o":["by","into","with","from"],"a":1},
        {"id":10,"q":"The whole nation was _________ the president.","o":["behind","after","against","above"],"a":0},
        {"id":11,"q":"Choose the correct sentence:","o":["He don't like football.","He doesn't likes football.","He doesn't like football.","He don't likes football."],"a":2},
        {"id":12,"q":"Choose the word that best fits: Despite his ________ efforts, the project failed.","o":["careless","diligent","lazy","poor"],"a":1},
        {"id":13,"q":"Fill in with correct preposition: She is afraid _____ spiders.","o":["for","of","from","with"],"a":1},
        {"id":14,"q":"Identify the figure of speech: The wind whispered through the trees.","o":["Simile","Metaphor","Personification","Alliteration"],"a":2},
        {"id":15,"q":"Mira volunteers at animal shelter on weekends. Her dedication inspires others. What quality is highlighted?","o":["Selfishness","Laziness","Kindness","Anger"],"a":2},
        {"id":16,"q":"Choose correct passive form: They will finish the work tomorrow.","o":["The work is finished tomorrow.","The work will be finished tomorrow.","The work was finished tomorrow.","The work has been finished tomorrow."],"a":1},
        {"id":17,"q":"Choose the synonym of OBSTACLE:","o":["advantage","hurdle","benefit","help"],"a":1},
        {"id":18,"q":"Choose the correctly punctuated sentence:","o":["Lets eat grandma.","Let's eat grandma.","Let's eat, grandma.","Lets eat, grandma."],"a":2},
        {"id":19,"q":"Fill in the blank: He has been working here ______ 2015.","o":["for","since","from","until"],"a":1},
        {"id":20,"q":"Choose the correct word: She was ______ by the news.","o":["surprise","surprised","surprising","surprises"],"a":1},
        {"id":21,"q":"If all mammals are warm-blooded, and dolphins are mammals, which is true?","o":["Dolphins are cold-blooded.","All dolphins are fish.","Dolphins are warm-blooded.","Mammals are cold-blooded."],"a":2},
        {"id":22,"q":"Ali chose studying over partying. What does this show?","o":["He is irresponsible.","He is lazy.","He is disciplined.","He is careless."],"a":2},
        {"id":23,"q":"Identify the error: She don't want to go.","o":["She","don't","want","go"],"a":1},
        {"id":24,"q":"Choose correct form: Neither of the boys ______ ready.","o":["are","is","were","be"],"a":1},
        {"id":25,"q":"Choose the antonym of VIGOROUS:","o":["weak","strong","active","energetic"],"a":0},
        {"id":26,"q":"Fill in: He _______ his keys yesterday.","o":["lose","lost","loses","losing"],"a":1},
        {"id":27,"q":"Sara paints to relax and express feelings. Why does she paint?","o":["To earn money","To relax and express feelings","To compete","To pass time"],"a":1},
        {"id":28,"q":"Choose correct conjunction: I wanted to go, ______ it started raining.","o":["but","and","or","so"],"a":0},
        {"id":29,"q":"Identify the adjective: The quick brown fox jumps over the lazy dog.","o":["jumps","fox","quick","over"],"a":2},
        {"id":30,"q":"Fill in: If I ______ rich, I would travel the world.","o":["am","were","was","be"],"a":1}
    ]
};

// Export for use in main script
if (typeof module !== 'undefined' && module.exports) {
    module.exports = QUESTION_BANK;
} 